version: "3.4"

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  processor:
    image: processor:latest
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - .env
    environment:
      - INDEXER_ENDPOINT_URL=${INDEXER_ENDPOINT_URL}
      - WS_URL=${WS_URL}
      - DB_HOST=db
      - POLL_INTERVAL_MS=300
      - TYPEORM_LOGGING=error
    ports:
      - 44233:44233
    command: ["yarn", "process"]

  query-node:
    image: query-node:latest
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - 4000:4000
    depends_on:
      - db
