apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - args:
            - --insecure
          image: cockroachdb/cockroach:v22.2.2
          name: db
          command: ["start-single-node"]
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/cockroach/data
              name: db-claim0
          ports:
            - name: dash
              containerPort: 8080
              protocol: TCP
              targetPort: 8080
            - name: db
              containerPort: 26257
              protocol: TCP
              targetPort: 26257
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: {{if .Values.volume.existingpersistentVolumeClaim }} {{.Values.volume.existingpersistentVolumeClaim}} {{ else }} tfchainindexer-volume-claim-{{ .Release.Name }} {{ end }}
status: {}
