apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: indexer
  name: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indexer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: indexer
    spec:
      containers:
        - args:
            - -e
            - {{ .Values.ws_endpoint }}
            - -c
            - "20"
            - --out
            - postgres://postgres:postgres@db:5432/squid-archive
            - --types-bundle
            - /configs/typesBundle.json
          image: subsquid/substrate-ingest:firesquid
          name: indexer
          resources: {}
          volumeMounts:
            - mountPath: /configs/typesBundle.json
              name: indexer-config
              subPath: typesBundle.json
      volumes:
        - name: indexer-config
          configMap:
            name: indexer-config
      restartPolicy: Always
status: {}
