apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: indexer-gateway
  name: indexer-gateway
spec:
  ports:
    - name: "8880"
      port: 8880
      targetPort: 8000
  selector:
    io.kompose.service: indexer-gateway
status:
  loadBalancer: {}
