apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: indexer-gateway
  name: indexer-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indexer-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: indexer-gateway
    spec:
      containers:
        - args:
            - --database-url
            - postgres://postgres:postgres@db:5432/squid-archive
            - --database-max-connections
            - '3'
          image: tmcgroul/substrate-gateway:16
          name: indexer-gateway
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
