apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: processor-db
  name: processor-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processor-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: processor-db
    spec:
      containers:
      - env:
          - name: POSTGRES_DB
            valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: processor-env
          - name: POSTGRES_PASSWORD
            valueFrom:
                configMapKeyRef:
                  key: DB_PASS
                  name: processor-env
          - name: POSTGRES_USER
            valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: processor-env
        image: postgres:12
        name: processor-db
        ports:
          - containerPort: 5432
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-claim-processor
      restartPolicy: Always
      volumes:
        - name: db-claim-processor
          persistentVolumeClaim:
            claimName: {{if .Values.volume.existingpersistentVolumeClaim }} {{.Values.volume.existingpersistentVolumeClaim}} {{ else }} {{ include "processor.fullname" . }}-db {{ end }}
status: {}
