# Default values for backendchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  processor:
    repository: ghcr.io/threefoldtech/tfchain_graphql_processor
    pullPolicy: IfNotPresent
    tag: ""
  query-node:
    repository: ghcr.io/threefoldtech/tfchain_graphql_query-node
    pullPolicy: IfNotPresent
    tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

promService:
  type: ClusterIP
  port: 23100

global:
  ingress:
    certresolver: le

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: tfchain.dev.threefold.io
      paths:
        - /graphql
  tls:
    - hosts:
        - tfchain.dev.threefold.io
      secretName: tfchain-dev-threefold-io-tls

ingresstest:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: tfchain.dev.threefold.io
      paths:
        - /graphql
  tls:
    - hosts:
        - tfchain.dev.threefold.io
      secretName: tfchain-dev-threefold-io-tls

# db host of the processor-db service
db_host: processor-db

# points to local indexer-gateway
indexer_endpoint: http://indexer-gateway:4010/v1/graphql

# ws_url: wss://tfchain.test.grid.tf
ws_url: 

volume:
  size: 5Gi
  existingpersistentVolumeClaim: ""
  persistentVolume:
    create: true
    hostPath: "/tfchainprocessor"

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

threefoldVdc:
  backup: ""
