name: Publish Docker images

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata processor
        id: metaprocessor
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}_processor
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push processor image
        uses: docker/build-push-action@v3
        with:
          push: true
          target: processor
          tags: ${{ steps.metaprocessor.outputs.tags }}
          labels: ${{ steps.metaprocessor.outputs.labels }}

      - name: Extract metadata query-node
        id: metaquerynode
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}_query-node
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push query-node image
        uses: docker/build-push-action@v3
        with:
          push: true
          target: query-node
          tags: ${{ steps.metaquerynode.outputs.tags }}
          labels: ${{ steps.metaquerynode.outputs.labels }}
